### ISSUE TITLE
`Invoke-Publish.ps1` requires `-ModuleManifestPath`

### ISSUE THREAD

**Issue by leojonathanoh** [theohbrothers/PSModulePublisher#25] opened 2023-03-22 07:13 UTC
## Current 

`Invoke-Publish.ps1` requires `-ModuleManifestPath`

## Discussion

`Invoke-Build.ps1` is an entrypoint script on its own that detects the module manifest automatically.

However, `Invoke-Publish.ps1`  despite being an entrypoint script, does not detect `-ModuleManifestPath` automatically.

**Comment by joeltimothyoh** [comment] 2023-03-26 23:58
`Invoke-Build.ps1` returns the module manifest path which is used for `Invoke-Test.ps1` and `Invoke-Publish.ps1`: https://github.com/theohbrothers/PSModulePublisher/blob/aa99891eac2de091060b8435fd23762163bb75e3/src/Invoke-PSModulePublisher.ps1#L34

`Invoke-PSModulePublisher.ps1` is actually the only entrypoint script for the project.

**Comment by leojonathanoh** [comment] 2023-03-27 04:53
The reason is because i recently used `v0.5.0`, see the [github CI file](https://github.com/theohbrothers/Generate-DockerImageVariants/blob/v0.4.6/.github/workflows/ci-master-pr.yml). Jobs:
-` test-*` which may call `./test/test.ps1` directly, or `Invoke-Test.ps1` of `PSModulePublisher` which does the same
- `test-publish-to-psgallery` which does a dry run `Invoke-Build.ps1` and `Invoke-Publish.ps1`. These are nice to use, except they needed params as described in OP. Ideally, one could simply do `Import-Module PSModulePublisher; Invoke-Build; Invoke-Publish -Dryrun` (without any other params since everything is auto-detected) which will be very elegant.
- `publish-to-psgallery` which is identical to `test-publish-to-psgallery` except it omits `-DryRun`.

**Comment by joeltimothyoh** [comment] 2023-03-27 10:28
Removing the `-ModuleManifestPath` param from `Invoke-Test.ps1` and `Invoke-Publish.ps1` means the scripts would be limited to processing only manifests from hard-coded paths. Presently the source of truth of the module manifest file is derived from first executing `Invoke-Build.ps1`. Because the project was designed where all `3` scripts are used within its offered CI templates, bypassing `Invoke-Build.ps1` means having to self-manage the parent project's module manifest directory.

The project utilizing the GitHub CI file you reference [uses `Invoke-Build.ps1` but does not assign the script's returned value (the module manifest path) to a variable](https://github.com/theohbrothers/Generate-DockerImageVariants/blob/e451a6ef7564577ec56568fb18bb44a07ca2d40c/.github/workflows/ci-master-pr.yml). Simply assign the value to a variable for use with `Invoke-Publish.ps1`.

**Comment by joeltimothyoh** [comment] 2023-04-12 09:33
Closing.

**Closed by joeltimothyoh** 2023-04-12 09:33 UTC
Labels: enhancement
